// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consigment/consigment.proto

/*
Package consigment is a generated protocol buffer package.

It is generated from these files:
	proto/consigment/consigment.proto

It has these top-level messages:
	Container
	Command
	Response
	GetRequest
*/
package consigment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Container struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
	Origin     string `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	UserId     string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Command struct {
	Id          string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Weight      int32        `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Containers  []*Container `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
	Vessel      string       `protobuf:"bytes,5,opt,name=vessel" json:"vessel,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Command) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Command) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Command) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Command) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Command) GetVessel() string {
	if m != nil {
		return m.Vessel
	}
	return ""
}

type Response struct {
	Created  bool       `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Command  *Command   `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Commands []*Command `protobuf:"bytes,3,rep,name=commands" json:"commands,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Response) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Container)(nil), "consigment.Container")
	proto.RegisterType((*Command)(nil), "consigment.Command")
	proto.RegisterType((*Response)(nil), "consigment.Response")
	proto.RegisterType((*GetRequest)(nil), "consigment.GetRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ShippingService service

type ShippingServiceClient interface {
	CreateCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	GetAllCommands(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CreateCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/consigment.ShippingService/CreateCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetAllCommands(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/consigment.ShippingService/GetAllCommands", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingService service

type ShippingServiceServer interface {
	CreateCommand(context.Context, *Command) (*Response, error)
	GetAllCommands(context.Context, *GetRequest) (*Response, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CreateCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consigment.ShippingService/CreateCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_GetAllCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GetAllCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consigment.ShippingService/GetAllCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GetAllCommands(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consigment.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCommand",
			Handler:    _ShippingService_CreateCommand_Handler,
		},
		{
			MethodName: "GetAllCommands",
			Handler:    _ShippingService_GetAllCommands_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consigment/consigment.proto",
}

func init() { proto.RegisterFile("proto/consigment/consigment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4b, 0x4e, 0xc3, 0x30,
	0x14, 0x24, 0xfd, 0xa5, 0x7d, 0x81, 0x22, 0x19, 0x28, 0x16, 0x1b, 0x4a, 0x56, 0xdd, 0xd0, 0x4a,
	0x45, 0xec, 0x58, 0x80, 0xba, 0xa8, 0xba, 0x75, 0x0f, 0x80, 0x4a, 0xfc, 0x94, 0x5a, 0x6a, 0xec,
	0x60, 0xbb, 0xe5, 0x02, 0x5c, 0x80, 0x2b, 0x70, 0x52, 0x14, 0x3b, 0x69, 0x83, 0x28, 0xbb, 0x37,
	0x6f, 0x26, 0x6f, 0x66, 0x22, 0xc3, 0x5d, 0xae, 0x95, 0x55, 0x93, 0x44, 0x49, 0x23, 0xd2, 0x0c,
	0xa5, 0xad, 0x8d, 0x63, 0xc7, 0x11, 0x38, 0x6c, 0xe2, 0x0c, 0x7a, 0x33, 0x25, 0xed, 0x4a, 0x48,
	0xd4, 0xa4, 0x0f, 0x0d, 0xc1, 0x69, 0x30, 0x0c, 0x46, 0x3d, 0xd6, 0x10, 0x9c, 0xdc, 0x42, 0x94,
	0x6c, 0x8d, 0x55, 0x19, 0xea, 0x57, 0xc1, 0x69, 0xc3, 0x11, 0x50, 0xad, 0x16, 0x9c, 0x0c, 0xa0,
	0xa3, 0xb4, 0x48, 0x85, 0xa4, 0x4d, 0xc7, 0x95, 0x88, 0x5c, 0x43, 0xb8, 0x35, 0xfe, 0xa3, 0x96,
	0x27, 0x0a, 0xb8, 0xe0, 0xf1, 0x77, 0x00, 0xe1, 0x4c, 0x65, 0xd9, 0x4a, 0xf2, 0x3f, 0x6e, 0x43,
	0x88, 0x38, 0x9a, 0x44, 0x8b, 0xdc, 0x0a, 0x25, 0x4b, 0xb7, 0xfa, 0xaa, 0xb0, 0xfb, 0x40, 0x91,
	0xae, 0xad, 0xb3, 0x6b, 0xb3, 0x12, 0x91, 0x47, 0x28, 0x2a, 0xf9, 0x12, 0x86, 0xb6, 0x86, 0xcd,
	0x51, 0x34, 0xbd, 0x1a, 0xd7, 0x7a, 0xef, 0x2b, 0xb2, 0x9a, 0xb0, 0x38, 0xb7, 0x43, 0x63, 0x70,
	0x43, 0xdb, 0x3e, 0xa4, 0x47, 0xf1, 0x67, 0x00, 0x5d, 0x86, 0x26, 0x57, 0xd2, 0x20, 0xa1, 0x10,
	0x26, 0x1a, 0x57, 0x16, 0x7d, 0xd4, 0x2e, 0xab, 0x20, 0xb9, 0x87, 0x30, 0xf1, 0x55, 0x5c, 0xd6,
	0x68, 0x7a, 0xf1, 0xdb, 0xd2, 0x51, 0xac, 0xd2, 0x90, 0x09, 0x74, 0xcb, 0xd1, 0xd0, 0xa6, 0x8b,
	0x78, 0x54, 0xbf, 0x17, 0xc5, 0xa7, 0x00, 0x73, 0xb4, 0x0c, 0xdf, 0xb7, 0x68, 0xec, 0xf4, 0x2b,
	0x80, 0xf3, 0xe5, 0x5a, 0xe4, 0xb9, 0x90, 0xe9, 0x12, 0xf5, 0x4e, 0x24, 0x48, 0x9e, 0xe0, 0x6c,
	0xe6, 0xc2, 0x54, 0xbf, 0xf4, 0xd8, 0xc5, 0x9b, 0xcb, 0xfa, 0xb2, 0xea, 0x15, 0x9f, 0x90, 0x67,
	0xe8, 0xcf, 0xd1, 0xbe, 0x6c, 0x36, 0xa5, 0xd0, 0x90, 0x41, 0x5d, 0x79, 0xf0, 0xfe, 0xef, 0xc2,
	0x5b, 0xc7, 0xbd, 0xa7, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xca, 0x26, 0x18, 0x74,
	0x02, 0x00, 0x00,
}
